<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE us-patent-assignments [
<!ELEMENT us-patent-assignments (action-key-code, transaction-date, patent-assignments)>
<!ATTLIST us-patent-assignments  dtd-version   CDATA  #IMPLIED
                                 date-produced CDATA  #IMPLIED>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (date)>
<!ELEMENT patent-assignments (data-available-code | patent-assignment+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT patent-assignment (assignment-record, patent-assignors, patent-assignees, patent-properties)>
<!ELEMENT assignment-record (reel-no, frame-no, last-update-date, purge-indicator, recorded-date, page-count?, correspondent, conveyance-text)>
<!ELEMENT patent-assignors (patent-assignor+)>
<!ELEMENT patent-assignees (patent-assignee+)>
<!ELEMENT patent-properties (patent-property+)>
<!ELEMENT reel-no (#PCDATA)>
<!ELEMENT frame-no (#PCDATA)>
<!ELEMENT last-update-date (date)>
<!ELEMENT purge-indicator (#PCDATA)>
<!ELEMENT recorded-date (date)>
<!ELEMENT page-count (#PCDATA)>
<!ELEMENT correspondent (name, address-1?, address-2?, address-3?, address-4?)>
<!ELEMENT conveyance-text (#PCDATA)>
<!ELEMENT patent-assignor (name, execution-date?, date-acknowledged?)>
<!ELEMENT patent-assignee (name, address-1?, address-2?, city?, state?, country-name?, postcode?)>
<!ELEMENT patent-property (document-id*, invention-title?)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name name-type (natural | legal)  #IMPLIED>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT address-2 (#PCDATA)>
<!ELEMENT address-3 (#PCDATA)>
<!ELEMENT address-4 (#PCDATA)>
<!ELEMENT execution-date (date)>
<!ELEMENT date-acknowledged (date)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT document-id (country, doc-number, kind?, name?, date?)>
<!ELEMENT invention-title (#PCDATA | b | i | u | sup | sub)*>
<!ATTLIST invention-title  id   ID     #IMPLIED
                           lang CDATA  #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT doc-number (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!--bold formatting for text-->
<!ELEMENT b (#PCDATA | i | u | smallcaps)*>
<!--italic formatting for text-->
<!ELEMENT i (#PCDATA | b | u | smallcaps)*>
<!--underscore: style - single is default-->
<!ELEMENT u (#PCDATA | b | i | smallcaps)*>
<!ATTLIST u  style  (single | double | dash | dots )  'single' >
<!--superscripted text-->
<!ELEMENT sup (#PCDATA | b | u | i)*>
<!--subscripted text-->
<!ELEMENT sub (#PCDATA | b | u | i)*>
<!--small capitals-->
<!ELEMENT smallcaps (#PCDATA | b | u | i)*>
]>
<us-patent-assignments dtd-version="0.3" date-produced="20031112">
<action-key-code>DA</action-key-code>
<transaction-date><date>20120622</date></transaction-date>
<patent-assignments>
<patent-assignment><assignment-record><reel-no>26423</reel-no><frame-no>144</frame-no><last-update-date><date>20120622</date></last-update-date><purge-indicator>N</purge-indicator><recorded-date><date>20110608</date></recorded-date><page-count>4</page-count><correspondent><name>MICHAEL D. KAMINSKI</name><address-1>FOLEY &amp; LARDNER LLP</address-1><address-2>3000 K STREET, N.W.</address-2><address-3>SUITE 600</address-3><address-4>WASHINGTON, D.C. 20007-5143</address-4></correspondent><conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text></assignment-record><patent-assignors><patent-assignor><name>WATANABE, KENTARO</name><execution-date><date>20110607</date></execution-date></patent-assignor><patent-assignor><name>MARUTSUKI, GIICHI</name><execution-date><date>20110607</date></execution-date></patent-assignor><patent-assignor><name>YAMAKAMI, YUYA</name><execution-date><date>20110607</date></execution-date></patent-assignor></patent-assignors><patent-assignees><patent-assignee><name>NICHIA CORPORATION</name><address-1>491-100, OKA, KAMINAKA-CHO</address-1><city>TOKUSHIMA, ANAN-SHI, 774-8601</city><country-name>JAPAN</country-name></patent-assignee></patent-assignees><patent-properties><patent-property><document-id><country>US</country><doc-number>13156150</doc-number><kind>X0</kind><date>20110608</date></document-id><document-id><country>US</country><doc-number>20110303894</doc-number><kind>A1</kind><date>20111215</date></document-id><invention-title lang="en">SEMICONDUCTOR LIGHT EMITTING ELEMENT AND FABRICATION METHOD</invention-title></patent-property></patent-properties></patent-assignment>
<patent-assignment><assignment-record><reel-no>27765</reel-no><frame-no>861</frame-no><last-update-date><date>20120622</date></last-update-date><purge-indicator>N</purge-indicator><recorded-date><date>20120209</date></recorded-date><page-count>18</page-count><correspondent><name>JAMES MURRAY</name><address-1>CT LIEN SOLUTIONS</address-1><address-2>4400 EASTON COMMONS WAY, SUITE 125</address-2><address-3>COLUMBUS, OH  43219</address-3></correspondent><conveyance-text>SECURITY AGREEMENT</conveyance-text></assignment-record><patent-assignors><patent-assignor><name>PHYSIO-CONTROL, INC.</name><execution-date><date>20120130</date></execution-date></patent-assignor></patent-assignors><patent-assignees><patent-assignee><name>BANK OF NEW YORK MELLON TRUST COMPANY, N.A., AS *COLLATERAL TRUSTEE, THE</name><address-1>601 TRAVIS STREET, 18TH FLOOR</address-1><city>HOUSTON</city><state>TEXAS</state><postcode>USA 77002</postcode></patent-assignee></patent-assignees><patent-properties><patent-property><document-id><country>US</country><doc-number>09978831</doc-number><kind>X0</kind><date>20011015</date></document-id><document-id><country>US</country><doc-number>20030073919</doc-number><kind>A1</kind><date>20030417</date></document-id><document-id><country>US</country><doc-number>6648833</doc-number><kind>B2</kind><date>20031118</date></document-id><invention-title lang="en">RESPIRATORY ANALYSIS WITH CAPNOGRAPHY</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>10121442</doc-number><kind>X0</kind><date>20020410</date></document-id><document-id><country>US</country><doc-number>20030195567</doc-number><kind>A1</kind><date>20031016</date></document-id><document-id><country>US</country><doc-number>6990373</doc-number><kind>B2</kind><date>20060124</date></document-id><invention-title lang="en">AUTOMATED EXTERNAL DEFIBRILLATOR WITH USER INTERFACE FOR ADULT AND PEDIATRIC APPLICATIONS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>10357267</doc-number><kind>X0</kind><date>20030131</date></document-id><document-id><country>US</country><doc-number>20040172068</doc-number><kind>A1</kind><date>20040902</date></document-id><document-id><country>US</country><doc-number>8036742</doc-number><kind>B2</kind><date>20111011</date></document-id><invention-title lang="en">APPARATUS AND METHODS FOR FIBRILLATION AND DEFIBRILLATION</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09658080</doc-number><kind>X0</kind><date>20000911</date></document-id><document-id><country>US</country><doc-number>6292687</doc-number><kind>B1</kind><date>20010918</date></document-id><invention-title lang="en">Medical emergency response and locating system</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>07888041</doc-number><kind>X0</kind><date>19920522</date></document-id><document-id><country>US</country><doc-number>5309909</doc-number><kind>B1</kind><date>19940510</date></document-id><invention-title lang="en">COMBINED SKIN PREPARATION AND MONITORING ELECTRODE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013236</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>5951483</doc-number><kind>B1</kind><date>19990914</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR DETECTING AN INTERNAL PACEMAKER PULSE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09761307</doc-number><kind>X0</kind><date>20010116</date></document-id><document-id><country>US</country><doc-number>20010051817</doc-number><kind>A1</kind><date>20011213</date></document-id><document-id><country>US</country><doc-number>6487448</doc-number><kind>B2</kind><date>20021126</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR CONVERTING A MONOPHASIC DEFIBRILLATOR TO A BIPHASIC DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08268629</doc-number><kind>X0</kind><date>19940630</date></document-id><document-id><country>US</country><doc-number>5456710</doc-number><kind>B1</kind><date>19951010</date></document-id><invention-title lang="en">VENTED ELECTRODE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08209774</doc-number><kind>X0</kind><date>19940311</date></document-id><document-id><country>US</country><doc-number>5496349</doc-number><kind>B1</kind><date>19960305</date></document-id><invention-title lang="en">METHOD AND SYSTEM FOR AUTOMATIC OR SEMI-AUTOMATIC DEFILBRILLATION USING REDUNDANT PROCESSING</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08334623</doc-number><kind>X0</kind><date>19941104</date></document-id><document-id><country>US</country><doc-number>5549659</doc-number><kind>B1</kind><date>19960827</date></document-id><invention-title lang="en">COMMUNICATION INTERFACE FOR TRANSMITTING AND RECEIVING SERIAL DATA BETWEEN MEDICAL INSTRUMENTS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08207854</doc-number><kind>X0</kind><date>19940308</date></document-id><document-id><country>US</country><doc-number>5574252</doc-number><kind>B1</kind><date>19961112</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR ELECTRICALLY AND MECHANICALLY INTERCONNECTING ELECTRICAL COMPONENTS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08209948</doc-number><kind>X0</kind><date>19940311</date></document-id><document-id><country>US</country><doc-number>5579234</doc-number><kind>B1</kind><date>19961126</date></document-id><invention-title lang="en">SYSTEM FOR AUTOMATICALLY TESTING AN ELECTRONIC DEVICE DURING QUIESCENT PERIODS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08334845</doc-number><kind>X0</kind><date>19941104</date></document-id><document-id><country>US</country><doc-number>5582180</doc-number><kind>B1</kind><date>19961210</date></document-id><invention-title lang="en">COMBINATION THREE-TWELVE LEAD ELECTROCARDIOGRAM CABLE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08188240</doc-number><kind>X0</kind><date>19940126</date></document-id><document-id><country>US</country><doc-number>5640078</doc-number><kind>B1</kind><date>19970617</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR AUTOMATICALLY SWITCHING AND CHARGING MULTIPLE BATTERIES</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08585159</doc-number><kind>X0</kind><date>19960111</date></document-id><document-id><country>US</country><doc-number>5713925</doc-number><kind>B1</kind><date>19980203</date></document-id><invention-title lang="en">ADAPTER FOR ISOLATING PACING AND DEFIBRILLATION SIGNALS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08632177</doc-number><kind>X0</kind><date>19960415</date></document-id><document-id><country>US</country><doc-number>5716380</doc-number><kind>B1</kind><date>19980210</date></document-id><invention-title lang="en">COMMON THERAPY/DATA PORT FOR A PORTABLE DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08643467</doc-number><kind>X0</kind><date>19960506</date></document-id><document-id><country>US</country><doc-number>5741305</doc-number><kind>B1</kind><date>19980421</date></document-id><invention-title lang="en">KEYED SELF-LATCHING BATTERY PACK FOR A PORTABLE DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08770629</doc-number><kind>X0</kind><date>19961219</date></document-id><document-id><country>US</country><doc-number>5748427</doc-number><kind>B1</kind><date>19980505</date></document-id><invention-title lang="en">METHOD AND SYSTEM FOR DETECTING RELAY FAILURE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08334787</doc-number><kind>X0</kind><date>19941104</date></document-id><document-id><country>US</country><doc-number>5787155</doc-number><kind>B1</kind><date>19980728</date></document-id><invention-title lang="en">PRIORITY LINE SWITCHING SYSTEM</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08811833</doc-number><kind>X0</kind><date>19970305</date></document-id><document-id><country>US</country><doc-number>5824017</doc-number><kind>B1</kind><date>19981020</date></document-id><invention-title lang="en">H-BRIDGE CIRCUIT FOR GENERATING A HIGH-ENERGY BIPHASIC WAVEFORM IN AN EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08837606</doc-number><kind>X0</kind><date>19970421</date></document-id><document-id><country>US</country><doc-number>5868790</doc-number><kind>B1</kind><date>19990209</date></document-id><invention-title lang="en">KEYED SELF-LATCHING BATTERY PACK FOR A PORTABLE DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08735728</doc-number><kind>X0</kind><date>19961023</date></document-id><document-id><country>US</country><doc-number>5872497</doc-number><kind>B1</kind><date>19990216</date></document-id><invention-title lang="en">HIGH ENERGY TRANSFER RELAY</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08811834</doc-number><kind>X0</kind><date>19970305</date></document-id><document-id><country>US</country><doc-number>5873893</doc-number><kind>B1</kind><date>19990223</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR VERIFYING THE INTEGRITY OF AN OUTPUT CIRCUIT BEFORE AND DURING APPLICATION OF A DEFIBRILLATION PULSE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08948630</doc-number><kind>X0</kind><date>19971009</date></document-id><document-id><country>US</country><doc-number>5921938</doc-number><kind>B1</kind><date>19990713</date></document-id><invention-title lang="en">SYSTEM AND METHOD FOR ADJUSTING TIME ASSOCIATED WITH MEDICAL EVENT DATA</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08984389</doc-number><kind>X0</kind><date>19971203</date></document-id><document-id><country>US</country><doc-number>5935152</doc-number><kind>B1</kind><date>19990810</date></document-id><invention-title lang="en">PORTABLE DEFIBRILLATOR HAVING RETRACTABLE HOOKS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08914865</doc-number><kind>X0</kind><date>19970819</date></document-id><document-id><country>US</country><doc-number>5983137</doc-number><kind>B1</kind><date>19991109</date></document-id><invention-title lang="en">METHOD AND SYSTEM FOR MONITORING THE CONDITION OF A BATTERY PACK IN A DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09062192</doc-number><kind>X0</kind><date>19980417</date></document-id><document-id><country>US</country><doc-number>5999852</doc-number><kind>B1</kind><date>19991207</date></document-id><invention-title lang="en">DEFIBRILLATOR METHOD AND APPARATUS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013805</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>6005370</doc-number><kind>B1</kind><date>19991221</date></document-id><invention-title lang="en">AUTOMATIC RATE CONTROL FOR DEFIBRILLATOR CAPACITOR CHARGING</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09035690</doc-number><kind>X0</kind><date>19980305</date></document-id><document-id><country>US</country><doc-number>6041254</doc-number><kind>B1</kind><date>20000321</date></document-id><invention-title lang="en">H-BRIDGE CIRCUIT FOR GENERATING A HIGH-ENERGY BIPHASIC WAVEFORM IN AN EXTERNAL DEFIBRILLATOR AND FURTHER INCLUDING A PROTECTIVE COMPONENT THAT HAS BOTH INDUCTIVE AND RESISTIVE PROPERTIES</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09237193</doc-number><kind>X0</kind><date>19990126</date></document-id><document-id><country>US</country><doc-number>6072299</doc-number><kind>B1</kind><date>20000606</date></document-id><invention-title lang="en">SMART BATTERY WITH MAINTENANCE AND TESTING FUNCTIONS, COMMUNICATIONS, AND DISPLAY</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>08755968</doc-number><kind>X0</kind><date>19961125</date></document-id><document-id><country>US</country><doc-number>6073085</doc-number><kind>B1</kind><date>20000606</date></document-id><invention-title lang="en">SYSTEM FOR AUTOMATICALLY TESTING AN ELECTRONIC DEVICE DURING QUIESCENT PERIODS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013569</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>6127063</doc-number><kind>B1</kind><date>20001003</date></document-id><invention-title lang="en">INTELLIGENT BATTERY AND WELL INTERFACE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09306644</doc-number><kind>X0</kind><date>19990506</date></document-id><document-id><country>US</country><doc-number>6133787</doc-number><kind>B1</kind><date>20001017</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR CONTROLLING THE COMMON MODE IMPEDANCE MISBALANCE OF AN ISOLATED SINGLE-ENDED CIRCUIT</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013409</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>6137261</doc-number><kind>B1</kind><date>20001024</date></document-id><invention-title lang="en">RECHARGEABLE BATTERY MAINTENANCE AND TESTING SYSTEM</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09209879</doc-number><kind>X0</kind><date>19981211</date></document-id><document-id><country>US</country><doc-number>6171256</doc-number><kind>B1</kind><date>20010109</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR DETECTING A CONDITION ASSOCIATED WITH ACUTE CARDIAC ISCHEMIA</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09170860</doc-number><kind>X0</kind><date>19981013</date></document-id><document-id><country>US</country><doc-number>6173204</doc-number><kind>B1</kind><date>20010109</date></document-id><invention-title lang="en">SEMICONDUCTOR ASSISTED RELAY IN A BIPHASIC DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09287483</doc-number><kind>X0</kind><date>19990406</date></document-id><document-id><country>US</country><doc-number>6175765</doc-number><kind>B1</kind><date>20010116</date></document-id><invention-title lang="en">H-BRIDGE CIRCUIT FOR GENERATING A HIGH-ENERGY BIPHASIC WAVEFORM IN AN EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013570</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>6185450</doc-number><kind>B1</kind><date>20010206</date></document-id><invention-title lang="en">DIGITAL SLIDING POLE FAST-RESTORE FOR AN ELECTROCARDIOGRAPH DISPLAY</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09471695</doc-number><kind>X0</kind><date>19991223</date></document-id><document-id><country>US</country><doc-number>6198253</doc-number><kind>B1</kind><date>20010306</date></document-id><invention-title lang="en">SMART BATTERY WITH MAINTENANCE AND TESTING FUNCTIONS, COMMUNICATIONS, AND DISPLAY</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09172322</doc-number><kind>X0</kind><date>19981013</date></document-id><document-id><country>US</country><doc-number>6208895</doc-number><kind>B1</kind><date>20010327</date></document-id><invention-title lang="en">CIRCUIT FOR PERFORMING EXTERNAL PACING AND BIPHASIC DEFIBRILLATION</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09170923</doc-number><kind>X0</kind><date>19981013</date></document-id><document-id><country>US</country><doc-number>6212429</doc-number><kind>B1</kind><date>20010403</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR CONVERTING A MONOPHASIC DEFIBRILLATOR TO A BIPHASIC DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09229977</doc-number><kind>X0</kind><date>19990113</date></document-id><document-id><country>US</country><doc-number>6217525</doc-number><kind>B1</kind><date>20010417</date></document-id><invention-title lang="en">REDUCED LEAD SET DEVICE AND METHOD FOR DETECTING ACUTE CARDIAC ISCHEMIC CONDITIONS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09013142</doc-number><kind>X0</kind><date>19980126</date></document-id><document-id><country>US</country><doc-number>6223077</doc-number><kind>B1</kind><date>20010424</date></document-id><invention-title lang="en">AUTOMATIC POWER SWITCHING IN A DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09232044</doc-number><kind>X0</kind><date>19990115</date></document-id><document-id><country>US</country><doc-number>6249696</doc-number><kind>B1</kind><date>20010619</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR INCREASING THE LOW FREQUENCY DYNAMIC RANGE OF A DIGITAL ECG MEASURING SYSTEM</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09246625</doc-number><kind>X0</kind><date>19990208</date></document-id><document-id><country>US</country><doc-number>6280391</doc-number><kind>B1</kind><date>20010828</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR REMOVING BASELINE WANDER FROM AN ECG SIGNAL</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09316468</doc-number><kind>X0</kind><date>19990521</date></document-id><document-id><country>US</country><doc-number>6304773</doc-number><kind>B1</kind><date>20011016</date></document-id><invention-title lang="en">AUTOMATIC DETECTION AND REPORTING OF CARDIAC ASYSTOLE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09389672</doc-number><kind>X0</kind><date>19990902</date></document-id><document-id><country>US</country><doc-number>6304779</doc-number><kind>B1</kind><date>20011016</date></document-id><invention-title lang="en">METHOD AND SYSTEM FOR PROVIDING A WARNING OF A REMAINING ENERGY LEVEL OF A BATTERY PACK IN A DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09444037</doc-number><kind>X0</kind><date>19991119</date></document-id><document-id><country>US</country><doc-number>6334070</doc-number><kind>B1</kind><date>20011225</date></document-id><invention-title lang="en">VISUAL AND AURAL USER INTERFACE FOR AN AUTOMATED EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09590459</doc-number><kind>X0</kind><date>20000609</date></document-id><document-id><country>US</country><doc-number>6400984</doc-number><kind>B1</kind><date>20020604</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR DETECTING WHETHER A LOAD IS A PATIENT OR A TEST DEVICE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09516426</doc-number><kind>X0</kind><date>20000301</date></document-id><document-id><country>US</country><doc-number>6421563</doc-number><kind>B1</kind><date>20020716</date></document-id><invention-title lang="en">SOLID-STATE MULTIPHASIC DEFIBRILLATION CIRCUIT</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09410198</doc-number><kind>X0</kind><date>19990930</date></document-id><document-id><country>US</country><doc-number>6440082</doc-number><kind>B1</kind><date>20020827</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR USING HEART SOUNDS TO DETERMINE THE PRESENCE OF A PULSE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09706578</doc-number><kind>X0</kind><date>20001103</date></document-id><document-id><country>US</country><doc-number>6477413</doc-number><kind>B1</kind><date>20021105</date></document-id><invention-title lang="en">H-BRIDGE CIRCUIT FOR GENERATING A HIGH-ENERGY BIPHASIC WAVEFORM IN AN EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09684506</doc-number><kind>X0</kind><date>20001006</date></document-id><document-id><country>US</country><doc-number>6539258</doc-number><kind>B1</kind><date>20030325</date></document-id><invention-title lang="en">ENERGY ADJUSTING CIRCUIT FOR PRODUCING AN ULTRA-LOW ENERGY DEFIBRILLATION WAVEFORM WITH FIXED PULSE WIDTH AND FIXED TILT</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09152837</doc-number><kind>X0</kind><date>19980914</date></document-id><document-id><country>US</country><doc-number>6594634</doc-number><kind>B1</kind><date>20030715</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR REPORTING EMERGENCY INCIDENTS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>10035297</doc-number><kind>X0</kind><date>20011026</date></document-id><document-id><country>US</country><doc-number>20030080712</doc-number><kind>A1</kind><date>20030501</date></document-id><document-id><country>US</country><doc-number>6639381</doc-number><kind>B2</kind><date>20031028</date></document-id><invention-title lang="en">DIFIBRILLATOR WITH REPLACEABLE AND RECHARGEABLE POWER PACKS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09841183</doc-number><kind>X0</kind><date>20010423</date></document-id><document-id><country>US</country><doc-number>20020183790</doc-number><kind>A1</kind><date>20021205</date></document-id><document-id><country>US</country><doc-number>6650936</doc-number><kind>B2</kind><date>20031118</date></document-id><invention-title lang="en">METHOD AND APPARATUS FOR DELIVERING ELECTROTHERAPY HAVING AN EQUIVALENT PROBABILITY OF SUCCESS FOR DIFFERENT PATIENTS</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09972028</doc-number><kind>X0</kind><date>20011004</date></document-id><document-id><country>US</country><doc-number>6697671</doc-number><kind>B1</kind><date>20040224</date></document-id><invention-title lang="en">VISUAL AND AURAL USER INTERFACE FOR AN AUTOMATED EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09945229</doc-number><kind>X0</kind><date>20010831</date></document-id><document-id><country>US</country><doc-number>20030045905</doc-number><kind>A1</kind><date>20030306</date></document-id><document-id><country>US</country><doc-number>6714817</doc-number><kind>B2</kind><date>20040330</date></document-id><invention-title lang="en">HARD PADDLE FOR AN EXTERNAL DEFIBRILLATOR</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09963100</doc-number><kind>X0</kind><date>20010924</date></document-id><document-id><country>US</country><doc-number>20030058097</doc-number><kind>A1</kind><date>20030327</date></document-id><document-id><country>US</country><doc-number>6727814</doc-number><kind>B2</kind><date>20040427</date></document-id><invention-title lang="en">SYSTEM, METHOD AND APPARATUS FOR SENSING AND COMMUNICATING STATUS INFORMATION FROM A PORTABLE MEDICAL DEVICE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09919783</doc-number><kind>X0</kind><date>20010731</date></document-id><document-id><country>US</country><doc-number>20030025602</doc-number><kind>A1</kind><date>20030206</date></document-id><document-id><country>US</country><doc-number>6747556</doc-number><kind>B2</kind><date>20040608</date></document-id><invention-title lang="en">METHOD AND SYSTEM FOR LOCATING A PORTABLE MEDICAL DEVICE</invention-title></patent-property><patent-property><document-id><country>US</country><doc-number>09945333</doc-number><kind>X0</kind><date>20010831</date></document-id><document-id><country>US</country><doc-number>20020072774</doc-number><kind>A1</kind><date>20020613</date></document-id><document-id><country>US</country><doc-number>6